# GitHub Projects
# Generated on 2026-06-13 22:41:32
# Total projects: 4



[[project]]
name = "markview"
description = "A beautiful Markdown previewer with syntax highlighting and instant rendering."
created = "Jul 2026"
pushed = "Jul 2026"
stars = 0
forks = 0
language = "CSS, JavaScript, HTML, Shell"
links = [
  { name = "URL", url = "https://markview.pankajkumar.xyz/" },
  { name = "GitHub", url = "https://github.com/ipankajkumar93/markview" },
]
highlight = true


[[project]]
name = "covidTracker"
description = "Automated covid vaccination slots look up in India by choosing PIN codes"
created = "May 2021"
pushed = "Mar 2023"
stars = 2
forks = 2
language = "TypeScript, HTML, JavaScript"
links = [
  { name = "URL", url = "https://www.trackcovid19.info/" },
  { name = "GitHub", url = "https://github.com/ipankajkumar93/covidtracker" },
]
highlight = true

[[project]]
name = "website"
description = "Personal site, made using Zola-Slate"
created = "Jun 2021"
pushed = "Jun 2026"
stars = 2
forks = 0
language = "HTML, Python, JavaScript, Shell"
links = [
  { name = "URL", url = "https://pankajkumar.xyz" },
  { name = "GitHub", url = "https://github.com/ipankajkumar93/website" },
]
highlight = false

[[project]]
name = "homeLab"
description = "HomeLab set up"
created = "Sept 2025"
pushed = "Sept 2025"
stars = 2
forks = 2
language = "Markdown"
links = [
  { name = "GitHub", url = "https://github.com/ipankajkumar93/homeLab" },
]

[[project]]
name = "Zola-Slate"
description = "Zola based template for Blogs"
created = "June 2026"
pushed = "Jul 2026"
stars = 0
forks = 0
language = "HTML, Python, JavaScript, Shell"
links = [
  { name = "URL", url = "https://zola-slate.pankajkumar.xyz" },
  { name = "GitHub", url = "https://github.com/ipankajkumar93/zola-slate" },
]
highlight = true